name: Health Check

# on:
#   schedule:
#     - cron: "20 7 31 12 *"

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-v8dx.onrender.com