name: Health Check

on:
  schedule:
    - cron: "20 5,6,7 * * *"  # At 05:20, 06:20 and 07:20 every day
  push:
    # Just for testing, can be removed later
    branches:
      - main

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-v8dx.onrender.com